# inventory Service Port
server:
port: 9003

flyway:
enabled: true
locations: classpath:migration
schemas: [inventory_db]

spring:
application:
name: inventory-service
datasource:
url: jdbc:mysql://localhost:3306/inventory_db
username: root
password: admin
jpa:
show-sql: true
hibernate:
ddl-auto: update

# Discovery Server Access
eureka:
client:
serviceUrl:
defaultZone: http://localhost:9001/eureka/
register-with-eureka: true
fetch-registry: true

archive:
path: E:\ARCHIVE